### ISSUE TITLE
Does not work on Android 2.2

### ISSUE THREAD

**Issue by andybalaam** [andybalaam/rabbit-escape#29]
We claim we work on Android 2.2 but today I received a crash notification showing that the version of the Java library in Android 2.2 does not have methods that we use:

    java.lang.NoSuchMethodError: java.lang.String.isEmpty
        at rabbitescape.render.AnimationLoader.readAnimation(AnimationLoader.java:121)
        at rabbitescape.render.AnimationLoader.load(AnimationLoader.java:102)
        at rabbitescape.render.AnimationCache.<init>(AnimationCache.java:20)
        at rabbitescape.ui.android.AndroidGraphics.<init>(AndroidGraphics.java:83)
        at rabbitescape.ui.android.AndroidGameLaunch.<init>(AndroidGameLaunch.java:60)
        at rabbitescape.ui.android.Game.<init>(Game.java:29)
        at rabbitescape.ui.android.GameSurfaceView.surfaceCreated(GameSurfaceView.java:77)
        at android.view.SurfaceView.updateWindow(SurfaceView.java:540)
        at android.view.SurfaceView.dispatchDraw(SurfaceView.java:339)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1375)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1375)
        at android.view.View.draw(View.java:6742)
        at android.widget.FrameLayout.draw(FrameLayout.java:352)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1648)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1375)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1646)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1375)
        at android.view.View.draw(View.java:6742)
        at android.widget.FrameLayout.draw(FrameLayout.java:352)
        at android.view.ViewGroup.drawChild(ViewGroup.java:1648)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:1375)
        at android.view.View.draw(View.java:6742)
        at android.widget.FrameLayout.draw(FrameLayout.java:352)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.draw(PhoneWindow.java:1872)
        at android.view.ViewRoot.draw(ViewRoot.java:1422)
        at android.view.ViewRoot.performTraversals(ViewRoot.java:1167)
        at android.view.ViewRoot.handleMessage(ViewRoot.java:1744)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:143)
        at android.app.ActivityThread.main(ActivityThread.java:4914)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:521)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
        at dalvik.system.NativeStart.main(Native Method)

I need to figure out an automated test for this, because it is bound to happen again as I only have an Android 2.3 phone to test on.

**Comment by andybalaam** [comment]
Alternatively, we could only declare support for 2.3 upwards, but I'd rather not do that.

**Comment by colonelfazackerley** [comment]
Virtual Machine of some sort?

2.2 is used by a small and diminishing group
https://en.wikipedia.org/wiki/Android_version_history#/media/File:Android_historical_version_distribution_-_vector.svg

even 2.3 is around 5% and shrinking.

**Comment by andybalaam** [comment]
Yeah, but I love those guys.

**Comment by andybalaam** [comment]
Fixed in release v0.4.2 1ddaec1cff9ab7f2e29f64174a08654f9f0ee0ef
